//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Mimo.Dbcontext.DBloginservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebDBConfigServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebDBConfigService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WS_AUTHENDB_DBConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback WS_AUTHENDB_USERConfigOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebDBConfigService() {
            this.Url = global::Mimo.Dbcontext.Properties.Settings.Default.Mimo_DbContext_dbloginservice_WebDBConfigService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WS_AUTHENDB_DBConfigCompletedEventHandler WS_AUTHENDB_DBConfigCompleted;
        
        /// <remarks/>
        public event WS_AUTHENDB_USERConfigCompletedEventHandler WS_AUTHENDB_USERConfigCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS_AUTHENDB_DBConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatabaseAccount WS_AUTHENDB_DBConfig(string strProjectID) {
            object[] results = this.Invoke("WS_AUTHENDB_DBConfig", new object[] {
                        strProjectID});
            return ((DatabaseAccount)(results[0]));
        }
        
        /// <remarks/>
        public void WS_AUTHENDB_DBConfigAsync(string strProjectID) {
            this.WS_AUTHENDB_DBConfigAsync(strProjectID, null);
        }
        
        /// <remarks/>
        public void WS_AUTHENDB_DBConfigAsync(string strProjectID, object userState) {
            if ((this.WS_AUTHENDB_DBConfigOperationCompleted == null)) {
                this.WS_AUTHENDB_DBConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS_AUTHENDB_DBConfigOperationCompleted);
            }
            this.InvokeAsync("WS_AUTHENDB_DBConfig", new object[] {
                        strProjectID}, this.WS_AUTHENDB_DBConfigOperationCompleted, userState);
        }
        
        private void OnWS_AUTHENDB_DBConfigOperationCompleted(object arg) {
            if ((this.WS_AUTHENDB_DBConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS_AUTHENDB_DBConfigCompleted(this, new WS_AUTHENDB_DBConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WS_AUTHENDB_USERConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAccount WS_AUTHENDB_USERConfig(string strProjectID) {
            object[] results = this.Invoke("WS_AUTHENDB_USERConfig", new object[] {
                        strProjectID});
            return ((UserAccount)(results[0]));
        }
        
        /// <remarks/>
        public void WS_AUTHENDB_USERConfigAsync(string strProjectID) {
            this.WS_AUTHENDB_USERConfigAsync(strProjectID, null);
        }
        
        /// <remarks/>
        public void WS_AUTHENDB_USERConfigAsync(string strProjectID, object userState) {
            if ((this.WS_AUTHENDB_USERConfigOperationCompleted == null)) {
                this.WS_AUTHENDB_USERConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS_AUTHENDB_USERConfigOperationCompleted);
            }
            this.InvokeAsync("WS_AUTHENDB_USERConfig", new object[] {
                        strProjectID}, this.WS_AUTHENDB_USERConfigOperationCompleted, userState);
        }
        
        private void OnWS_AUTHENDB_USERConfigOperationCompleted(object arg) {
            if ((this.WS_AUTHENDB_USERConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS_AUTHENDB_USERConfigCompleted(this, new WS_AUTHENDB_USERConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DatabaseAccount {
        
        private string databaseNameField;
        
        private string serverNameField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string statusField;
        
        private string detailField;
        
        /// <remarks/>
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAccount {
        
        private string userNameField;
        
        private string passwordField;
        
        private string domainNameField;
        
        private string statusField;
        
        private string detailField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WS_AUTHENDB_DBConfigCompletedEventHandler(object sender, WS_AUTHENDB_DBConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS_AUTHENDB_DBConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS_AUTHENDB_DBConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatabaseAccount Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatabaseAccount)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WS_AUTHENDB_USERConfigCompletedEventHandler(object sender, WS_AUTHENDB_USERConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS_AUTHENDB_USERConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS_AUTHENDB_USERConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAccount Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAccount)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591